insert into ville (nom, cp) values ('Sudislavl’', '157860');
insert into ville (nom, cp) values ('Phichit', '18000');
insert into ville (nom, cp) values ('Porangaba', '18260-000');
insert into ville (nom, cp) values ('Penápolis', '16300-000');
insert into ville (nom, cp) values ('Fukuyama', '999-8241');
insert into ville (nom, cp) values ('Uddiawan', '3605');
insert into ville (nom, cp) values ('Amsterdam Oud Zuid en Rivierenbuurt', '1079');
insert into ville (nom, cp) values ('Birmingham', '35254');
insert into ville (nom, cp) values ('Soroca', 'MD-4901');
insert into ville (nom, cp) values ('Karlshamn', '374 33');
insert into ville (nom, cp) values ('Vitória da Conquista', '45000-000');
insert into ville (nom, cp) values ('Bigaan', '6105');
insert into ville (nom, cp) values ('San José de Jáchal', '5461');
insert into ville (nom, cp) values ('Pontes e Lacerda', '78250-000');
insert into ville (nom, cp) values ('Krasnodar', '385129');
insert into ville (nom, cp) values ('Jalaud', '1045');
insert into ville (nom, cp) values ('Kuanda', '674170');
insert into ville (nom, cp) values ('Preobrazheniye', '429500');
insert into ville (nom, cp) values ('Kungälv', '442 12');
insert into ville (nom, cp) values ('Ceres', '2340');
insert into ville (nom, cp) values ('Bayaguana', '11207');
insert into ville (nom, cp) values ('Melaka', '75552');
insert into ville (nom, cp) values ('Niebocko', '36-207');
insert into ville (nom, cp) values ('Stockholm', '103 98');
insert into ville (nom, cp) values ('Khosta', '354395');
insert into ville (nom, cp) values ('Nongoma', '3950');
insert into ville (nom, cp) values ('Suraż', '18-105');
insert into ville (nom, cp) values ('Camocim', '62400-000');
insert into ville (nom, cp) values ('Drochia', 'MD-5233');
insert into ville (nom, cp) values ('Tres Isletas', '4000');
insert into ville (nom, cp) values ('Vila Franca', '4935-621');
insert into ville (nom, cp) values ('Santa Maria', '25903');
insert into ville (nom, cp) values ('Santana de Parnaíba', '06500-000');
insert into ville (nom, cp) values ('Cambarus', '1259');
insert into ville (nom, cp) values ('Gudja', 'GDJ');
insert into ville (nom, cp) values ('Verbilki', '141930');
insert into ville (nom, cp) values ('Bromma', '168 00');
insert into ville (nom, cp) values ('Leipzig', '04109');
insert into ville (nom, cp) values ('Kaminokawa', '899-2421');
insert into ville (nom, cp) values ('Habo', '566 24');
insert into ville (nom, cp) values ('Calibungan', '2312');
